#!/bin/bash
# Post-provision hook: Generate .env file for local development

echo ""
echo "==================================================="
echo "Prism infrastructure deployed successfully!"
echo "==================================================="
echo ""

# Get all values from azd env (these are also exported as env vars by azd)
ENV_NAME=$(azd env get-value AZURE_ENV_NAME 2>/dev/null || echo "$AZURE_ENV_NAME")
STORAGE_ACCOUNT_NAME=$(azd env get-value AZURE_STORAGE_ACCOUNT_NAME 2>/dev/null || echo "$AZURE_STORAGE_ACCOUNT_NAME")
RESOURCE_GROUP=$(azd env get-value AZURE_RESOURCE_GROUP 2>/dev/null || echo "$AZURE_RESOURCE_GROUP")
AZURE_LOCATION=$(azd env get-value AZURE_LOCATION 2>/dev/null || echo "$AZURE_LOCATION")

# Get values for .env file
AZURE_OPENAI_KEY=$(azd env get-value AZURE_OPENAI_KEY 2>/dev/null || echo "$AZURE_OPENAI_KEY")
AZURE_OPENAI_ENDPOINT=$(azd env get-value AZURE_OPENAI_ENDPOINT 2>/dev/null || echo "$AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_MODEL_NAME=$(azd env get-value AZURE_OPENAI_MODEL_NAME 2>/dev/null || echo "$AZURE_OPENAI_MODEL_NAME")
AZURE_OPENAI_API_VERSION=$(azd env get-value AZURE_OPENAI_API_VERSION 2>/dev/null || echo "$AZURE_OPENAI_API_VERSION")
AZURE_OPENAI_CHAT_DEPLOYMENT_NAME=$(azd env get-value AZURE_OPENAI_CHAT_DEPLOYMENT_NAME 2>/dev/null || echo "$AZURE_OPENAI_CHAT_DEPLOYMENT_NAME")
AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME=$(azd env get-value AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME 2>/dev/null || echo "$AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME")
AZURE_SEARCH_ENDPOINT=$(azd env get-value AZURE_SEARCH_ENDPOINT 2>/dev/null || echo "$AZURE_SEARCH_ENDPOINT")
AZURE_SEARCH_ADMIN_KEY=$(azd env get-value AZURE_SEARCH_ADMIN_KEY 2>/dev/null || echo "$AZURE_SEARCH_ADMIN_KEY")
AZURE_STORAGE_ACCOUNT_URL=$(azd env get-value AZURE_STORAGE_ACCOUNT_URL 2>/dev/null || echo "$AZURE_STORAGE_ACCOUNT_URL")
AZURE_STORAGE_CONTAINER_NAME=$(azd env get-value AZURE_STORAGE_CONTAINER_NAME 2>/dev/null || echo "$AZURE_STORAGE_CONTAINER_NAME")
AUTH_PASSWORD=$(azd env get-value AUTH_PASSWORD 2>/dev/null || echo "$AUTH_PASSWORD")
APPLICATIONINSIGHTS_CONNECTION_STRING=$(azd env get-value APPLICATIONINSIGHTS_CONNECTION_STRING 2>/dev/null || echo "$APPLICATIONINSIGHTS_CONNECTION_STRING")

echo "Environment: $ENV_NAME"
echo "Resource Group: $RESOURCE_GROUP"
echo "Storage Account: $STORAGE_ACCOUNT_NAME"
echo ""

echo "Generating .env file for local development..."

# Write .env file with provisioned values
cat > .env << EOF
# Auto-generated by azd provision
# Environment: ${ENV_NAME}

# Azure OpenAI / AI Foundry
AZURE_OPENAI_API_KEY=${AZURE_OPENAI_KEY}
AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
AZURE_OPENAI_MODEL_NAME=${AZURE_OPENAI_MODEL_NAME}
AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
AZURE_OPENAI_CHAT_DEPLOYMENT_NAME=${AZURE_OPENAI_CHAT_DEPLOYMENT_NAME}
AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME=${AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME}

# Azure AI Search
AZURE_SEARCH_ENDPOINT=${AZURE_SEARCH_ENDPOINT}
AZURE_SEARCH_ADMIN_KEY=${AZURE_SEARCH_ADMIN_KEY}

# Azure Storage (Blob)
# - Local Docker: Uses Azurite emulator (connection string set in docker-compose)
# - Container Apps: Uses Managed Identity (DefaultAzureCredential)
AZURE_STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT_NAME}
AZURE_STORAGE_ACCOUNT_URL=${AZURE_STORAGE_ACCOUNT_URL}
AZURE_STORAGE_CONTAINER_NAME=${AZURE_STORAGE_CONTAINER_NAME}

# Authentication
AUTH_PASSWORD=${AUTH_PASSWORD}

# Monitoring (optional)
APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}
EOF

echo ""
echo "Resources created:"
echo "  Resource Group: ${RESOURCE_GROUP}"
echo "  Location: ${AZURE_LOCATION}"
echo "  Storage Account: ${STORAGE_ACCOUNT_NAME}"
echo ""
echo "Endpoints:"
echo "  Azure OpenAI: ${AZURE_OPENAI_ENDPOINT}"
echo "  Azure Search: ${AZURE_SEARCH_ENDPOINT}"
echo "  Storage: ${AZURE_STORAGE_ACCOUNT_URL}"
echo ""
echo ".env file created."
echo ""
echo "For local Docker development (uses Azurite storage emulator):"
echo "  docker-compose -f infra/docker/docker-compose.yml --env-file .env up -d"
echo ""
echo "For Azure Container Apps:"
echo "  azd deploy"
echo ""
